version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app                # Mount the current directory to /app in the container
      # - /app/node_modules      # Prevents overwriting node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
